export {
  MOTANS_CORPORATE_BRAND_ASSETS,
  MOTANS_CORPORATE_BRAND_ASSET_HASHES,
  MOTANS_CORPORATE_STAMP_PUBLIC_PATH,
  MOTANS_CORPORATE_ICON_M_PUBLIC_PATH,
  MOTANS_CORPORATE_MARK_MS_WEBP_PUBLIC_PATH,
  MOTANS_CORPORATE_MARK_MS_PNG_PUBLIC_PATH,
  type MotansCorporateBrandAssetKey,
} from "./motansBrandAssets.js";
